sudo: required
services:
  - docker

before_install:
  - docker build -t tonycruz/docker-react -f Dockerfile.dev .
script:
  - docker run -it tonycruz/docker-react npm run test -- --coverage  
deploy:
  provider: elasticbeanstalk  
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-249445456169"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"  
